### ISSUE TITLE
Possible to tag .lnk files?

### ISSUE THREAD

**Issue by jbrown1597** [Jamminroot/intag#22]
I'm having no problem with File Folders, but with shortcuts I'm having issues. Let's say I want the "Music" shortcut. 
Since it's not working via InTag, I manually go inside the shortcut folder, & I place my desktop.ini with the following parameters:

![dfdfd](https://github.com/Jamminroot/intag/assets/50437670/b62d2843-3d0e-41bd-a2d9-72ae77f5d8c5)

Save, and to my surprise- it's still unsuccessful.

![adfgsdfgsdfg](https://github.com/Jamminroot/intag/assets/50437670/182e894b-e4bc-4567-926b-db2710780d9f)

Any ideas? Appreciate you 💖
EDIT: Might be worth checking this out: https://exiftool.org/TagNames/LNK.html

**Comment by Jamminroot** [comment]
I'm afraid that this approach is not going to work, as MS Explorer sorts\groups items based on their _own_ tags\properties, meaning that it would only group `lnk` files if they have tags on themself (rather than objects they link to), which is impossible (`lnk` files mainly have properties related to how apps should behave in console).

However, there is a workaround for that: using symlinks. In simple terms, that is a way of making Windows treat objects in the links as if they were directly IN the folder. For example:
I have my sources in `D:\DEV`, and a symlink in drive 'C`: `C:\DEV` linked to it. And when I enter `C:\DEV`, explorer thinks that I actually work inside `C:\DEV\Intag` etc.

Note that some side effects can occur depending on what app you work in.

In disk `C`:

![image](https://github.com/Jamminroot/intag/assets/6387654/8e82346f-c790-491c-bf98-c628c54eefff)

Inside folder:

![image](https://github.com/Jamminroot/intag/assets/6387654/d84b84cf-9a67-44ec-9c63-37754428d6bd)

Creating a symlink is something like
`mklink /J D:\A C:\A` or `mklink /D DEV D:\DEV`; Not exactly sure which I used (was a while ago).
These are different modes, one makes "join" folders, other is just for directory links... That should be described [here](https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/mklink)
